### PR TITLE
Fix/color export Issue #61

### PR DESCRIPTION
**Pull request by apertureless**
Fixed the color export of the Color Inventory -> Export dialogue.
Now it will export it to the same destination als generate -> export.

### CODE REVIEW

**Comment by getflourish** [comment]
Thanks a lot! You are amazing!

**Comment by apertureless** [comment]
You're welcome!

**Comment by lokimuje** [comment]
it doesn't work..

**Comment by jeckart3d** [comment]
agreed. still doesn't work on 3.5.2

**Pull request merged**
